### PR TITLE
Add an inspect to Twirp::Service to get prettier `rails routes` output

### PR DESCRIPTION
**Pull request by danielmorrison**
Completes #5 

This lists all the handlers and methods like normal routes:

`/twirp/example/HaberdasherService  haberdasher_service_handler#make_hat`

### CODE REVIEW

**Review by gaffneyc — APPROVED** [review]
It seems legit though it feels odd to monkey patch inspect on a class from another gem. I'm sure it's fine though... would refinements be useful here?

**Comment by danielmorrison** [comment]
> It seems legit though it feels odd to monkey patch inspect on a class from another gem. I'm sure it's fine though... would refinements be useful here?

Ooh, maybe. I forgot those were at thing. Might have to put that nerd sniping off to another day…

**Comment by gaffneyc** [comment]
Just going to drop this here: https://docs.ruby-lang.org/en/master/syntax/refinements_rdoc.html

**Comment by gaffneyc** [comment]
Looks like this is the code the calls #inspect and formats the output: https://github.com/rails/rails/blob/a6bf6d55804850b390d840b87a679b784c0a3db4/actionpack/lib/action_dispatch/routing/inspector.rb#L15

**Comment by danielmorrison** [comment]
No, after spending a little time on this, I don't think refinements will work for us.

**Comment by danielmorrison** [comment]
I'm not huge on monkeypatching either, but if there's a clearer way here I don't know what it is. I've played with a few ideas unsuccessfully.

**Pull request merged**
